Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2023-09, with the labels that each got.

#767 feat: add action title
  __tests__/fileAction.spec.ts
  lib/fileAction.ts
Labels: enhancement, 3. to review

#768 Remove permission check in publish workflows
  .github/workflows/documentation.yml
  .github/workflows/npm-publish.yml
  package.json
Labels: 3. to review

#770 fix(formatFileSize): Fix default value for `binaryPrefixes`
  __tests__/humanFileSize.spec.ts
  lib/humanfilesize.ts
Labels: bug, 3. to review

#769 feat(parseFileSize): Added `parseFileSize` function to parse a human readable file size to number of bytes
  __tests__/humanFileSize.spec.ts
  lib/humanfilesize.ts
Labels: enhancement

#779 chore: Prepare new beta release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#780 docs: update documentation link
  README.md
Labels: bug, documentation, 3. to review
