Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2023-08, with the labels that each got.

#715 fix: Move to `@nextcloud/vite-config` after package was transfered
  package-lock.json
  package.json
  vite.config.ts
Labels: 3. to review

#716 fix(node): allow negative file ids
  __tests__/files/node.spec.ts
  lib/files/nodeData.ts
Labels: bug, 3. to review

#717 feat: add FileListHeader
  __tests__/fileListHeaders.spec.ts
  lib/fileListHeaders.ts
  lib/index.ts
  window.d.ts
Labels: enhancement, 3. to review

#724 fix: headers and actions empty variable init
  __tests__/fileAction.spec.ts
  __tests__/fileListHeaders.spec.ts
  lib/fileAction.ts
  lib/fileListHeaders.ts
Labels: bug, 3. to review

#732 feat: migrate Navigation and update FileAction from server
  __tests__/fileAction.spec.ts
  __tests__/newFileMenu.spec.ts
  lib/fileAction.ts
  lib/fileListHeaders.ts
  lib/index.ts
  lib/navigation/column.ts
  lib/navigation/navigation.ts
  lib/navigation/view.ts
  lib/newFileMenu.ts
  package-lock.json
  package.json
  tsconfig.json
  window.d.ts
Labels: 3. to review

#740 fix: force bundle `is-svg`
  vite.config.ts
Labels: bug, 3. to review

#742 fix(newfilemenu): fix handler requirement, deprecate iconClass and fix context
  lib/index.ts
  lib/newFileMenu.ts
Labels: bug, 3. to review

#743 Prepare new beta 19
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#744 feat(files): add node status
  __tests__/files/file.spec.ts
  __tests__/files/node.spec.ts
  lib/files/node.ts
  lib/files/nodeData.ts
  lib/index.ts
Labels: enhancement, 3. to review

#752 feat: provide fileList names as newFileMenu handler argument
  __tests__/newFileMenu.spec.ts
  lib/newFileMenu.ts
Labels: enhancement, 3. to review

#753 fix: use Node and not string for the new file menu handler arg
  lib/newFileMenu.ts
Labels: bug, 3. to review
