Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2023-07, with the labels that each got.

#681 fix: fileid definition and fallback
  __tests__/files/node.spec.ts
  lib/files/node.ts
Labels: bug

#682 chore: add lint-eslint.yml
  .eslintignore
  .eslintrc.js
  .github/workflows/lint-eslint.yml
  __tests__/fileAction.spec.ts
  __tests__/files/file.spec.ts
  __tests__/files/folder.spec.ts
  __tests__/files/node.spec.ts
  __tests__/humanFileSize.spec.ts
  __tests__/index.spec.ts
  __tests__/newFileMenu.spec.ts
  __tests__/permissions.spec.ts
  babel.config.js
  jest.config.js
  lib/fileAction.ts
  lib/files/file.ts
  lib/files/folder.ts
  lib/files/node.ts
  lib/files/nodeData.ts
  lib/humanfilesize.ts
  lib/index.ts
  lib/newFileMenu.ts
  lib/permissions.ts
  package-lock.json
  package.json
  rollup.config.mjs
  window.d.ts
Labels: 3. to review

#683 fix: allow undefined properties in File and Folder
  __tests__/files/node.spec.ts
  lib/files/nodeData.ts
Labels: 3. to review

#703 chore: Drop babel dependency - not used anyways
  babel.config.js
  package-lock.json
  package.json
Labels: 3. to review

#705 Use vite and vitest for bundling and testing the package
  .eslintrc.js
  .eslintrc.json
  .github/dependabot.yml
  .npmignore
  __tests__/fileAction.spec.ts
  __tests__/files/file.spec.ts
  __tests__/files/folder.spec.ts
  __tests__/files/node.spec.ts
  __tests__/humanFileSize.spec.ts
  __tests__/index.spec.ts
  __tests__/newFileMenu.spec.ts
  __tests__/permissions.spec.ts
  jest.config.js
  package-lock.json
  package.json
  rollup.config.mjs
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: 3. to review

#704 chore: Cleanup package and make it a native ESM package
  .eslintrc.js
  .eslintrc.json
  .github/dependabot.yml
  .npmignore
  jest.config.js
  package-lock.json
  package.json
  rollup.config.js
  tsconfig.json
Labels: 3. to review

#706 Add DAV functions for fetching nodes from Nextcloud
  __mocks__/@nextcloud/auth.js
  __mocks__/@nextcloud/router.js
  __tests__/dav/dav.spec.ts
  __tests__/dav/davPermissions.spec.ts
  __tests__/dav/davProperties.spec.ts
  __tests__/files/node.spec.ts
  __tests__/fixtures/favorites-inner-response.json
  __tests__/fixtures/favorites-inner-response.xml
  __tests__/fixtures/favorites-response.json
  __tests__/fixtures/favorites-response.xml
  __tests__/index.spec.ts
  lib/dav/dav.ts
  lib/dav/davPermissions.ts
  lib/dav/davProperties.ts
  lib/files/folder.ts
  lib/files/node.ts
  lib/files/nodeData.ts
  lib/humanfilesize.ts
  lib/index.ts
  lib/permissions.ts
  package-lock.json
  package.json
  window.d.ts
Labels: 3. to review

#708 docs: Add badge for documentation containing a link to it
  README.md
Labels: 3. to review

#709 fix: do not update mtime if not already defined
  __tests__/files/file.spec.ts
  lib/files/node.ts
Labels: bug, 3. to review

#712 fix: Bring back Typescript definitions
  vite.config.ts
Labels: 3. to review

#713 chore: Fix URLs after package got transfered
  CHANGELOG.md
  README.md
  package.json
Labels: 3. to review
