Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2023-12, with the labels that each got.

#847 fix(Node): Handle slash as root path for public webdav endpoint
  __tests__/files/node.spec.ts
  lib/files/node.ts
Labels: bug, 3. to review

#849 enh(dav): Allow to set custom headers when creating the DAV client
  lib/dav/dav.ts
Labels: enhancement, 3. to review

#855 chore: update workflows from templates
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review
