Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-07, with the labels that each got.

#1012 Migrate REUSE to TOML format
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 3. to review

#1014 test: Add missing test case for sorting equal values and ESLint warning
  __mocks__/@nextcloud/router.js
  __tests__/utils/sorting.spec.ts
Labels: bug, 3. to review

#1013 feat(filename): Improve filename validation to support Nextcloud 30 capabilities
  __tests__/utils/filename-validation.spec.ts
  __tests__/utils/filename.spec.ts
  lib/index.ts
  lib/utils/filename-validation.ts
  lib/utils/filename.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1019 feat(node): Add `displayname` as top level attribute
  __mocks__/@nextcloud/router.js
  __tests__/dav/dav.spec.ts
  __tests__/files/node.spec.ts
  __tests__/utils/fileSorting.spec.ts
  lib/dav/dav.ts
  lib/files/node.ts
  lib/files/nodeData.ts
Labels: enhancement, 3. to review

#1018 fix: `Node.move` should also adjust the displayname
  __tests__/dav/dav.spec.ts
  __tests__/files/node.spec.ts
  __tests__/utils/fileSorting.spec.ts
  lib/dav/dav.ts
  lib/files/node.ts
  lib/files/nodeData.ts
Labels: bug, 3. to review

#1020 chore: Prepare 3.6.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1028 fix(dav): Cast displayname to string in `resultToNode`
  lib/dav/dav.ts
Labels: bug, 3. to review

#1026 fix: Correctly export public API
  lib/index.ts
  lib/utils/fileSorting.ts
  lib/utils/sorting.ts
Labels: bug, 3. to review

#1027 feat: Implement API for file list filters
  .config/typedoc.json
  REUSE.toml
  lib/fileListFilters.ts
  lib/globals.d.ts
  lib/index.ts
  lib/navigation/index.ts
  package-lock.json
  package.json
  window.d.ts
Labels: enhancement, 3. to review

#1029 test: Add unit tests for file list filters
  __tests__/fileListFilter.spec.ts
  __tests__/tsconfig.json
Labels: 3. to review

#1030 chore: Prepare v3.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
