Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-06, with the labels that each got.

#974 fix(node): remove auto mtime update on attributes change and allow mtime set
  __tests__/files/file.spec.ts
  __tests__/files/node.spec.ts
  lib/files/node.ts
Labels: 3. to review

#975 3.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#980 Add SPDX headers
  .eslintignore
  .github/dependabot.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
  .gitignore
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/LGPL-3.0-or-later.txt
  LICENSES/MIT.txt
  README.md
  __mocks__/@nextcloud/auth.js
  __mocks__/@nextcloud/router.js
  __tests__/dav/dav.spec.ts
  __tests__/dav/davPermissions.spec.ts
  __tests__/dav/davProperties.spec.ts
  __tests__/fileAction.spec.ts
  __tests__/fileListHeaders.spec.ts
  __tests__/files/file.spec.ts
  __tests__/files/folder.spec.ts
  __tests__/files/node.spec.ts
  __tests__/index.spec.ts
  __tests__/newFileMenu.spec.ts
  __tests__/tsconfig.json.license
  __tests__/utils/fileSize.spec.ts
  __tests__/utils/filename.spec.ts
  lib/dav/dav.ts
  lib/dav/davPermissions.ts
  lib/dav/davProperties.ts
  lib/fileAction.ts
  lib/fileListHeaders.ts
  lib/files/file.ts
  lib/files/fileType.ts
  lib/files/folder.ts
  lib/files/node.ts
  lib/files/nodeData.ts
  lib/index.ts
  lib/navigation/column.ts
  lib/navigation/navigation.ts
  lib/navigation/view.ts
  lib/newFileMenu.ts
  lib/permissions.ts
  lib/utils/fileSize.ts
  lib/utils/fileSorting.ts
  lib/utils/logger.ts
  vite.config.ts
  vitest.config.ts
  window.d.ts
Labels: documentation, 3. to review

#985 fix(dav): Set `status` in `davResultToNode` when fileid is negative
  __tests__/dav/dav.spec.ts
  lib/dav/dav.ts
Labels: bug, 3. to review

#986 feat: Add filename util `getUniqueName` to generate a unique name
  __tests__/utils/filename.spec.ts
  lib/index.ts
  lib/utils/filename.ts
Labels: enhancement, 3. to review

#984 fix: When sorting by filename the extension should only be considered if the basename is equal
  __tests__/utils/fileSorting.spec.ts
  lib/utils/fileSorting.ts
Labels: bug, 3. to review

#976 feat: Export public interfaces of `Node`, `File` and `Folder`
  lib/files/file.ts
  lib/files/folder.ts
  lib/files/node.ts
  lib/index.ts
  lib/navigation/column.ts
  lib/navigation/navigation.ts
  lib/utils/fileSorting.ts
Labels: enhancement, 3. to review

#987 feat(navigation): Allow to listen for active navigation changes
  __tests__/navigation.spec.ts
  lib/navigation/navigation.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#990 chore: Prepare release of v3.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#991 fix(dav): Add `displayname` and `creationdate` to default props
  __tests__/dav/davProperties.spec.ts
  lib/dav/davProperties.ts
Labels: bug, 3. to review

#992 fix(sorting): The display name attribute is called `displayname` not `displayName` for DAV
  __tests__/utils/fileSorting.spec.ts
  lib/utils/fileSorting.ts
Labels: bug, 3. to review

#995 fix: Update development dependencies
  package-lock.json
  package.json
Labels: 3. to review

#996 fix: make `davRootPath` and `davRemoteURL` support public shares
  __tests__/dav/dav-public.spec.ts
  __tests__/dav/dav.spec.ts
  __tests__/dav/public-shares.spec.ts
  lib/dav/dav.ts
  lib/index.ts
  lib/utils/isPublic.ts
  package-lock.json
  package.json
Labels: bug, 3. to review

#997 chore: Prepare v3.5.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
