Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-09, with the labels that each got.

#1069 chore: Release v3.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1076 feat(FileAction): Allow to set `destructive` flag
  __tests__/fileAction.spec.ts
  lib/fileAction.ts
Labels: enhancement, 3. to review

#1075 fix: Document optional `user` property of FileListFilterChip
  lib/fileListFilters.ts
Labels: bug, 3. to review

#1074 Fixed deprecation warning `Node.attributes.displayname` should be accessed directly on the `Node`
  lib/utils/fileSorting.ts
Labels: bug, 3. to review

#1077 feat: Allow cloning a node
  lib/files/file.ts
  lib/files/folder.ts
  lib/files/node.ts
  lib/index.ts
  tsconfig.json
Labels: enhancement, 3. to review
