Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-12, with the labels that each got.

#1142 fix: Do not rollup types
  vite.config.ts
Labels: bug, 3. to review

#1135 fix(fileListAction): keep same method param pattern accross our APIs
  __tests__/fileListAction.spec.ts
  lib/fileListAction.ts
Labels: 3. to review

#1143 feat: Allow omitting icon for file list actions
  __tests__/fileListAction.spec.ts
  lib/fileListAction.ts
Labels: enhancement, 3. to review

#1144 3.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1145 fix: ensure FileListAction return `bool|null` on `exec`
  lib/fileListAction.ts
Labels: 3. to review
