Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-11, with the labels that each got.

#1097 feat: Allow registering actions for a file listing
  __tests__/fileListAction.spec.ts
  __tests__/view.spec.ts
  lib/fileListAction.ts
  lib/index.ts
  lib/navigation/view.ts
  window.d.ts
Labels: enhancement, 3. to review

#1112 test: Ensure time zone dependent tests run identically across environments
  __tests__/test-global-setup.ts
  vitest.config.ts
Labels: 3. to review

#1115 fix(dav): crtime parsing and invalid date handling
  __tests__/dav/dav.spec.ts
  lib/dav/dav.ts
Labels: bug, 3. to review

#1113 feat: Add current folder context for file list actions
  __tests__/fileListAction.spec.ts
  lib/fileListAction.ts
Labels: enhancement, 3. to review

#1025 refactor: Scope package into modules
  README.md
  __tests__/dav/dav.spec.ts
  __tests__/dav/davPermissions.spec.ts
  __tests__/dav/davProperties.spec.ts
  __tests__/dav/public-shares.spec.ts
  lib/dav/dav.ts
  lib/dav/davPermissions.ts
  lib/dav/davProperties.ts
  lib/dav/index.ts
  lib/index.ts
  package.json
  vite.config.ts
Labels: enhancement, question, 3. to review, breaking

#1116 feat: Add `reset` method to file list filters
  __tests__/fileListFilter.spec.ts
  lib/fileListFilters.ts
Labels: enhancement, 3. to review

#1117 chore: Prepare release of v3.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1119 fix: Typo in method name `isDavResource` instead of `isDavRessource`
  __tests__/dav/dav.spec.ts
  __tests__/dav/public-shares.spec.ts
  __tests__/files/file.spec.ts
  __tests__/files/folder.spec.ts
  __tests__/files/node.spec.ts
  lib/files/node.ts
  lib/files/nodeData.ts
Labels: bug, 3. to review
