Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2024-05, with the labels that each got.

#949 fix(navigation): files import
  lib/navigation/view.ts
Labels: bug, 3. to review

#947 feat(files): allow updating attributes
  __tests__/files/node.spec.ts
  lib/files/node.ts
Labels: 3. to review

#952 feat(new-menu): Allow to set the category for entries
  __tests__/newFileMenu.spec.ts
  lib/newFileMenu.ts
Labels: enhancement, 3. to review

#959 fix(dav): Add fallback for owner of dav nodes on public shares
  __tests__/dav/dav.spec.ts
  lib/dav/dav.ts
Labels: bug, 3. to review

#958 3.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#960 fix: Export `NewMenuEntryCategory` from package
  lib/index.ts
Labels: bug, 3. to review

#962 chore: Prepare 3.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#967 fix(Node): Do not drop readonly attributes but only forbid updating them
  __tests__/files/node.spec.ts
  lib/files/node.ts
Labels: bug, 3. to review

#968 chore: Add test case for file sorting of same display name
  __tests__/utils/fileSorting.spec.ts
Labels: 3. to review

#969 chore: Prepare 3.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
