Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2025-02, with the labels that each got.

#1183 chore(deps): typedoc-plugin-missing-exports as dev dependency
  package-lock.json
  package.json
Labels: type: bug, type: dependencies, 3. to review

#1184 chore: Prepare v3.10.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1197 fix(sorting): fallback basename to empty string just in case
  lib/utils/fileSorting.ts
Labels: type: bug, 3. to review
