Repository nextcloud-libraries/nextcloud-files, pull requests merged in 2025-07, with the labels that each got.

#1285 fix(sorting): also check attributes
  __tests__/utils/fileSorting.spec.ts
  lib/dav/dav.ts
  lib/utils/fileSorting.ts
Labels: type: bug, 3. to review

#1288 feat(actions): allow to define hotkey for file action
  lib/actions/fileAction.ts
  lib/actions/index.ts
Labels: type: enhancement, 3. to review

#1290 docs(View): improve documentation of `View.emptyView`
  lib/navigation/view.ts
Labels: type: documentation, 3. to review

#1292 chore: work around bug in `corepack` blocking dependency updates
  package.json
Labels: 3. to review
